[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
arrayvec = "0.7"
bitflags = "1.3"
clap = { version = "4.0", features = ["derive"]}
lazy_static = "1.4"
nom = "7.1"
rayon = "1.6"
